name= input("Enter your name: ")
age= input("Enter your age: ")
color= input("Enter your favorite color: ")
hobby= input("Enter your hobby: ")
print(f"Hi {name}! You are {age} years old, your favorite color is {color}, and you enjoy {hobby}.")